# Generated by Django 4.2.5 on 2023-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_note_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
